# Generated by Django 5.2.1 on 2025-05-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(
                blank=True, max_length=13, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
