# Generated by Django 5.2.1 on 2025-05-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_cnpj_supplier_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(
                blank=True, max_length=18, null=True, unique=True
            ),
        ),
    ]
