networks:
  sge-network:
    driver: bridge

services:
  db:
    image: postgres:15    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sge
    networks:
      - sge-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5    
  web:
    image: gimbss/sge_dmaster:latest
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - sge-network
    environment:
      - POSTGRES_DB=sge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=False
      - ALLOWED_HOSTS=144.22.136.249,localhost,127.0.0.1
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    networks:
      - sge-network
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: