# Generated by Django 5.2.1 on 2025-05-09 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_brand_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='decriotion',
            new_name='description',
        ),
    ]
