# Generated by Django 5.2.1 on 2025-05-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='decriotion',
            new_name='description',
        ),
    ]
