# Generated by Django 5.2.1 on 2025-05-08 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_alter_brand_options'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                (
                    'serial_number',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'cost_price',
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    'selling_price',
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'image',
                    models.ImageField(
                        blank=True, null=True, upload_to='products/images/'
                    ),
                ),
                (
                    'brand',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='brands.brand',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='categories.categorie',
                    ),
                ),
            ],
        ),
    ]
