# Generated by Django 5.2.1 on 2025-05-12 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0003_supplier_cnpj_supplier_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to='suppliers.supplier',
            ),
            preserve_default=False,
        ),
    ]
